wine-app-helper

diff --git a/wine-app-helper/wine-run b/wine-app-helper/wine-run
--- a/wine-app-helper/wine-run
+++ b/wine-app-helper/wine-run
@@ -12,14 +12,25 @@
 APP_TOP_DIR="/opt/wine-apps"
 WINE_DIR_PREFIX="/opt/wine"
 
+# App 名称
 APP_NAME=$(basename $0)
+# App 中文名称
 APP_NAME_CN=""
+# App 版本号
 APP_VERSION="1.0"
+# App 压缩包文件名
 APP_ARCHIVE=""
+# App 升级时需要忽略的文件列表
 APP_IGNORE=""
-APP_RUN_CMD=""
+# App 运行时需要进入的路径
 APP_RUN_PATH=""
+# App 运行命令
+APP_RUN_CMD=""
+# App 运行时使用的 wine 版本号
 APP_RUN_WINE=""
+
+OPT_RESET=n
+OPT_HELP=n
 
 APP_DIR=$APP_TOP_DIR/$APP_NAME
 
@@ -29,17 +40,6 @@ else
     zenity --error --text="出错啦！" --text="找不到 $APP_DIR/$APP_NAME.metainfo 文件，请检查安装包是否正确"
     exit
 fi
-
-#"""
-#APP_NAME=wine-cs            # App 名称
-#APP_NAME_CN=wine-cs         # App 中文名称
-#APP_VERSION=1.6             # App 版本号
-#APP_ARCHIVE=                # App 压缩包文件名
-#APP_IGNORE=                 # App 升级时需要忽略的文件列表
-#APP_RUN_CMD=                # App 运行命令
-#APP_RUN_PATH=               # App 运行时需要进入的路径
-#APP_RUN_WINE=6.0            # App 运行时使用的 wine 版本号
-#"""
 
 WINE_DIR=${WINE_DIR_PREFIX}-${APP_RUN_WINE}
 export WINEDLLPATH=$WINE_DIR/lib:$WINE_DIR/lib64
@@ -58,9 +58,20 @@ app_uninstall()
 
 usage()
 {
-    echo " Extra Commands:"
-    echo " -e/--remove    Remove extract app files"
-    echo " -h/--help      Show program help info"
+    cat << ENDLINE
+$0 [OPTIONS...]
+
+运行当前容器的默认应用程序-`basename $APP_RUN_CMD`
+
+Option:
+  -c --console  打开当前容器的终端
+  -f --winefile 打开当前容器的文件管理器
+  -s --winecfg  打开当前容器的设置工具
+  -r --regedit  打开当前容器的注册表
+  -t --taskmgr  打开当前容器的任务管理器
+  -e --reset    重置当前容器到首次安装状态
+  -h --help     显示帮助
+ENDLINE
 }
 
 fix_disk_link()
@@ -86,13 +97,15 @@ app_install()
 
 app_update()
 {
-    if [ -f "$WINEPREFIX/app_version" ] && [ "$(cat "$WINEPREFIX/app_version")" = "$APP_VERSION" ];then
+    if [ -f "$WINEPREFIX/app_version" ] && [ "$(cat "$WINEPREFIX/app_version")" = "$APP_VERSION" ]; then
         return
     fi
 
     tar xf $APP_DIR/$APP_ARCHIVE -C $WINEPREFIX --exclude-from=$APP_IGNORE
 
-    rm -rf $WINEPREFIX/drive_c/users/\@current_user\@
+    if [ -d "$WINEPREFIX/drive_c/users/@current_user@" ]; then
+        rm -rf "$WINEPREFIX/drive_c/users/@current_user@"
+    fi
 
     echo "$APP_VERSION" > "$WINEPREFIX/app_version"
 }
@@ -118,11 +131,78 @@ app_run()
 
 progressbar()
 {
-    WINDOWID="" zenity --progress --title="$1" --text="$2" --pulsate --width=400 --auto-close --no-cancel \
-        || WINDOWID="" zenity --progress --title="$1" --text="$2" --pulsate --width=400 --auto-close
+    WINDOWID="" zenity --progress --title="$1" --text="$2" --pulsate --width=400 --auto-close --no-cancel
 }
 
-########
+##################################
+set -o errexit -o pipefail -o noclobber -o nounset
+
+! getopt --test > /dev/null
+if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
+    echo 'I’m sorry, `getopt --test` failed in this environment.'
+    exit 1
+fi
+
+LONGOPTS=console,reset,winefile,winecfg,help,regedit,taskmgr
+OPTIONS=cefshrt
+
+! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+    exit 2
+fi
+eval set -- "$PARSED"
+
+while true; do
+    case "$1" in
+        -c|--console)
+            APP_RUN_PATH="drive_c/windows"
+            APP_RUN_CMD=wineconsole
+            shift
+            ;;
+        -e|--reset)
+            OPT_RESET=y
+            shift
+            ;;
+        -f|--winefile)
+            APP_RUN_PATH="drive_c/windows"
+            APP_RUN_CMD=winefile
+            shift
+            ;;
+        -r|--regedit)
+            APP_RUN_PATH="drive_c/windows"
+            APP_RUN_CMD=regedit
+            shift
+            ;;
+        -s|--winecfg)
+            APP_RUN_PATH="drive_c/windows"
+            APP_RUN_CMD=winecfg
+            shift
+            ;;
+        -t|--taskmgr)
+            APP_RUN_PATH="drive_c/windows"
+            APP_RUN_CMD=taskmgr
+            shift
+            ;;
+        -h|--help)
+            OPT_HELP=y
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Programming error"
+            exit 3
+            ;;
+    esac
+done
+
+if [ $OPT_HELP == "y" ];then
+    usage
+    exit 0
+fi
+
 if ! command -v zenity >/dev/null 2>&1;then
     echo "please install package zenity"
     exit 1
@@ -133,26 +213,8 @@ if [ $APP_NAME == "wine-run" ]; then
     exit 1
 fi
 
-if [ $# -gt 1 ];then
-    echo "Invalid option"
-    echo "Use -h|--help to get help"
-    exit 1
+if [ "x${OPT_RESET}" == "xy" ]; then
+    app_uninstall
+    exit
 fi
-
-if [ -n "$1" ];then
-    case $1 in
-        "-e" | "--remove")
-            app_uninstall
-            ;;
-        "-h" | "--help")
-            usage
-            ;;
-        *)
-            echo "Invalid option"
-            echo "Use -h|--help to get help"
-            exit 1
-            ;;
-    esac
-else
-    app_run
-fi
+app_run
